server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: zuul
zuul:
  routes:
    provider:
      path: provider/**
      serviceId: provider
    customer:
      path: customer/**
      serviceId: customer