server:
  port: 8090
spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?useUnicode\=true&characterEncoding\=UTF-8&useOldAliasMetadataBehavior\=true
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        min-idle: 1
        max-idle: 8
        max-wait: 1ms
        max-active: 8
mybatis:
  mapper-locations: mapping\UserMapper.xml
  type-aliases-package: com.garytry.customer.model
