server:
  port: 8763
eureka:
  instance:
   #主机名称（应用注册中心）
    hostname: peer2
  client:
    #服务注册中心相互注册一定要显示的设置register-with-eureka 和fetch-registry的值为true,否则会服务不可用
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #注册到pee1 eureka server
      defaultZone: http://peer1:8762/eureka/
spring:
  application:
    name: discovery