server:
  port: 8762
eureka:
  instance:
    #服务名称（应用注册中心）
    hostname: pee1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #注册到pee2 eureka server
      defaultZone: http://pee2:8763/eureka/
spring:
  application:
    name: discovery