server:
  port: 8762
eureka:
  instance:
    #主机名称（应用注册中心）
    hostname: pee1
  client:
    #服务注册中心相互注册一定要显示的设置register-with-eureka 和fetch-registry的值为true,否则会服务不可用
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #注册到pee2 eureka server
      defaultZone: http://pee2:8763/eureka/
spring:
  application:
    name: discovery